name: Count Lines of Code
on:
  push:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday

jobs:
  count_loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count lines of code
        run: |
          echo "Total lines of code:" > LOC.txt
          cloc --json . | jq '.SUM.code' >> LOC.txt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update lines of code count"
