name: Count Lines of Code
on:
  push:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday

jobs:
  count_loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cloc
        run: sudo apt install -y cloc

      - name: Count lines of code
        run: |
          LOC=$(cloc --json . | jq '.SUM.code')
          echo "![Lines of Code](https://img.shields.io/badge/Lines_of_Code-${LOC}-blue)" > LOC.md

      - name: Update README
        run: |
          sed -i '/<!-- LOC Badge -->/r LOC.md' README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update lines of code count"
